service: blastbanners
image: screenshotone/blastbanners

builder:
    context: .
    arch: amd64

servers:
    - <%= ENV["TARGET_HOST"] %>

logging:
    driver: loki
    options:
        loki-url: <%= ENV["LOKI_URL"] %>
        loki-retries: 5
        loki-batch-size: 400
        loki-external-labels: app=screenshotone-blastbanners,container_name={{.Name}}

volumes:
    - data:/app/data:rw

proxy:
    forward_headers: false
    healthcheck:
        interval: 3
        path: /health
        timeout: 3
    app_port: 3000

registry:
    server: <%= ENV["DOCKER_REGISTRY_SERVER"] %>
    username:
        - DOCKER_REGISTRY_USERNAME
    password:
        - DOCKER_REGISTRY_PASSWORD
